require "./ui/rect"
require "./ui/cell"
require "./ui/buffer"
require "./ui/layer"
require "./ui/layer_stack"
require "./ui/diff_renderer"

require "./ui/element"
require "./ui/input_hookable"
require "./ui/control"
require "./ui/engine"
require "./ui/components/text"
require "./ui/components/badge"
require "./ui/components/rule"
require "./ui/components/stack"
require "./ui/components/box"
require "./ui/components/table"
require "./ui/components/viewport"
require "./ui/components/sparkline"
require "./ui/components/barchart"
require "./ui/components/gauge"
require "./ui/components/tree"
require "./ui/components/modal"
require "./ui/components/toast"
require "./ui/components/filter_list"
require "./ui/components/command_palette"
require "./ui/components/split_view"
require "./ui/components/code_view"
require "./ui/components/tabs"
require "./ui/components/hex_viewer"
require "./ui/components/file_dialog"
require "./ui/components/color_picker"
require "./ui/components/color_picker_3d"
require "./ui/components/pie_chart"
require "./ui/components/line_graph"
require "./ui/components/ascii_image"
require "./ui/components/button"
require "./ui/components/dropdown"
require "./ui/components/scrollbar"
require "./ui/components/window"
require "./ui/components/canvas_2d"
require "./ui/components/mesh_3d"
require "./ui/components/switch"
require "./ui/components/checkbox"
require "./ui/components/slider"
require "./ui/components/radio_set"
require "./ui/components/collapsible"
require "./ui/components/digits"
require "./ui/components/rich_log"
require "./ui/components/loading_indicator"
require "./ui/components/header"
require "./ui/components/footer"
require "./ui/components/placeholder"
require "./ui/components/content_switcher"
require "./ui/components/binary_metrics"
require "./ui/layouts/dock"
require "./ui/layouts/grid"
require "./ui/screen"
require "./ui/screen_stack"
require "./ui/query"
require "./ui/dsl"

module Opal
  # Convenience shortcut to render a declarative UI tree
  def self.render_ui(width : Int32 = 80, height : Int32 = 24, &block : UI::Builder -> Nil) : String
    UI.render(width, height, &block)
  end
end
